name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Robot
        run: pip install robotframework
      # - name: RequestsLibrary
      #   run: pip install RequestsLibrary
      # - name: JSONLibrary
      #   run: pip install JSONLibrary
