neme: Teste de API

on:
  push:
    branches: [main]
    branches: [pipeline]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 11 * * 1,2,3,4,5'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
        - task: UsePythonVersion@0
        - script: pip install robotframework robotframework-seleniumlibrary && npm install chromedriver
        - powershell: robot -d logs tests/testUserPet.robot