neme: Teste de API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 11 * * 1,2,3,4,5'

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projeto
      uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0