name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Robot
        run: sudo pip install robotframework
      - name: RequestsLibrary
        run: sudo pip install requests
      - name: JSONLibrary
        run: sudo pip install robotframework-jsonlibrary
