neme: Teste de API

on:
  push:
    branches: [main]
    branches: [pipeline]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 11 * * 1,2,3,4,5'

stages:
  - Acceptance Tests
    tags:
        - docker
    before_script:
        - cat /etc/*-release
        - dnf upgrade -y >/dev/null && echo OK
        - dnf install -y python37 >/dev/null && echo OK
        - dnf install -y fedora-workstation-repositories >/dev/null && echo OK
        - dnf install -y 'dnf-command(config-manager)' >/dev/null && echo OK
        - dnf config-manager --set-enabled google-chrome >/dev/null && echo OK
        - dnf install -y google-chrome-stable >/dev/null && echo OK
        - pip3 install webdrivermanager >/dev/null && echo OK
        - webdrivermanager chrome >/dev/null && echo OK
        - pip3 install robotframework robotframework-seleniumlibrary | grep "Successfully installed"
        - python --version
        - google-chrome --version
        - chromedriver --version
    script:
        - robot -d logs -v BROWSER:headlesschrome testUserPet.robot