name: Teste de API
on: [push]
jobs:
  test:
      # criando uma execução ao mesmo tempo nas máquinas
    runs-on: ${{ matrix.os}}
    # criando uma execução ao mesmo tempo nas versões declaradas
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        py-version: ['3.8', '3.9', '>=3.10']
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
        # aqui é colocado as versões do python para rodar como matrix
          python-version: ${{ matrix.py-version}}
      - name: Instalando Robot
<<<<<<< HEAD
        run: pip install robotframework
      - name: Instalando RequestsLibrary
        run: pip install robotframework-requests
      - name: Instalando JSONLibrary
        run: pip install robotframework-jsonlibrary

=======
        run: pip install -r requirements.txt
>>>>>>> b1531d7c06ece834ebe1a5f9d0d3e748471fcb8c
      - name: Rodando o teste
        run: robot -d logs tests/testUserPet.robot
